services:
  redis:
    image: redis:latest
    container_name: notification_redis
    ports:
      - "6380:6379" # Expose Redis on port 6380 locally, map to 6379 in the container

  provider:
    build:
      context: ./provider
      dockerfile: Dockerfile
    container_name: provider
    command: ["npm", "run", "start"]
    ports:
      - "8071:8071"
      - "8072:8072"
      - "8073:8073"
      - "8091:8091"
      - "8092:8092"
      - "8093:8093"

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    command: ["npm", "run", "start"]
    depends_on:
      - redis
    environment:
      SERVER_PORT: 3001
      PROVIDER_HOST: provider
      REDIS_HOST: notification_redis
      REDIS_PORT: 6379
      SOCKETIO_PORT: 3002
    ports:
      - "3001:3001"
      - "3002:3002"

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client
    command: ["npm", "run", "dev"]
    depends_on:
      - server
    environment:
      NEXT_PUBLIC_SOCKETIO_URL: http://localhost:3002
    ports:
      - "3000:3000"
